### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by tpisto** [penberg/rusty_jsc#1]
Hi! Thank you for this impressive work! When searching for rust javascriptcore libs I found also this https://github.com/tauri-apps/javascriptcore-rs. How your library differentiate from theirs?

**Comment by penberg** [comment]
@tpisto Hey! Last time I tried it, it required GTK on macOS too and didn't support callbacks from JavaScript back to Rust code.

**Comment by penberg** [comment]
@tpisto Btw, I opened the discussions forum for the repository -- happy to continue the discussion there!
