### ISSUE TITLE
rusty_jsc 0.0.3 not in crates.io, but rusty_jsc_sys and rusty_jsc_macros are.

### ISSUE THREAD

**Issue by tpisto** [penberg/rusty_jsc#3]
If I upgrade using this git repo, I get errors:

5   | #[callback]
    | ^^^^^^^^^^^
    | |
    | expected struct `rusty_jsc_sys::OpaqueJSContext`, found struct `OpaqueJSContext`
    | arguments to this function are incorrect

**Comment by penberg** [comment]
Oh, sorry about that @tpisto, fixed.
